name: Linux Builds

on:
  push

jobs:
  AudioPerformanceTest:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target AudioPerformanceTest -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target AudioPerformanceTest -- -j4

  AudioPluginHost:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target AudioPluginHost -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target AudioPluginHost -- -j4

  BinaryBuilder:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target BinaryBuilder -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target BinaryBuilder -- -j4

  DemoRunner:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target DemoRunner -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target DemoRunner -- -j4

  NetworkGraphicsDemo:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target NetworkGraphicsDemo -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target NetworkGraphicsDemo -- -j4

  Projucer:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target Projucer -- -j4
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target Projucer -- -j4

  UnitTestRunner:
    runs-on: ubuntu-18.04
    container:
      image: kunitoki/juce:latest
      volumes:
        - ${{ github.workspace }}:/juce
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
          cmake --build cmake-build --target UnitTestRunner -- -j4
    - name: Unit Tests Debug
      shell: bash
      run: cmake-build/extras/UnitTestRunner/UnitTestRunner_artefacts/Debug/UnitTestRunner
    - name: Build Release
      shell: bash
      working-directory: /juce
      run: |
          cmake -B cmake-build -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build cmake-build --target UnitTestRunner -- -j4
    - name: Unit Tests Release
      shell: bash
      run: cmake-build/extras/UnitTestRunner/UnitTestRunner_artefacts/Release/UnitTestRunner
