name: Windows Builds

on:
  push

jobs:
  AudioPerformanceTest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target AudioPerformanceTest
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target AudioPerformanceTest

  AudioPluginHost:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target AudioPluginHost
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target AudioPluginHost

  BinaryBuilder:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target BinaryBuilder
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target BinaryBuilder

  DemoRunner:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target DemoRunner
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target DemoRunner

  NetworkGraphicsDemo:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target NetworkGraphicsDemo
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target NetworkGraphicsDemo

  Projucer:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target Projucer
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target Projucer

  UnitTestRunner:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      shell: bash
      run: |
        cmake -B cmake-debug -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build cmake-debug --target UnitTestRunner
    - name: Unit Tests Debug
      shell: bash
      run: cmake-debug/extras/UnitTestRunner/UnitTestRunner_artefacts/Debug/UnitTestRunner.exe
    - name: Build Release
      shell: bash
      run: |
        cmake -B cmake-release -DJUCE_BUILD_EXAMPLES=ON -DJUCE_BUILD_EXTRAS=ON -DCMAKE_BUILD_TYPE=Release
        cmake --build cmake-release --target UnitTestRunner
    - name: Unit Tests Release
      shell: bash
      run: cmake-release/extras/UnitTestRunner/UnitTestRunner_artefacts/Release/UnitTestRunner.exe
